---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant 
  vars_files:
    #- env_vars/base.yml
    - env_vars/local.yml
  #sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - postfix
    - php-fpm
    - memcached
    - wordpress
    - webgrind
    - backup
    - letsencrypt
    - sftp
